name: coding_challenge_verifier
description: A Dart microservice that verifies pull requests for coding challenges.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  crypto: ^3.0.3
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
  mockito: ^5.4.1
